name: Deploy Hugo Website
on: [push]
jobs:
  Build:
    runs-on: ubuntu-latest
    container:
      image: hugomods/hugo:0.125.2
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: hugo build
        run: |
          cd /__w/Shitbeer/Shitbeer
          echo "ls" && ls
          echo "pwd" && pwd
          hugo
      - name: hugo build upload
        uses: actions/upload-artifact@v4
        with:
          name: hugo-build
          retention-days: 1
          path: |
            public
  Deploy:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - name: hugo build download
        uses: actions/download-artifact@v4
        with:
          name: hugo-build
      - name: hugo deploy
        env:
          SSH_PRIVATE_KEY: ${{ secrets.OVH_VPS_SSH_PRIVATE_KEY}}
          SSH_IP: ${{ vars.OVH_VPS_SSH_IP}}
          SSH_PORT: ${{ vars.OVH_VPS_SSH_PORT}}
          SSH_USERNAME: ${{ vars.OVH_VPS_SSH_USERNAME}}
        run: |
          ssh-add - <<< "${SSH_PRIVATE_KEY}"
          rsync -avz --delete -e "ssh -p ${SSH_PORT}" public/ ${SSH_USERNAME}@${SSH_IP}:~/public/