name: Deploy Hugo Website
on: [push]
jobs:
  Deploy-Hugo-Website:
    runs-on: ubuntu-latest
    steps:
      - env:
          SSH_PRIVATE_KEY: ${{ secrets.OVH_VPS_SSH_PRIVATE_KEY}}
          SSH_IP: ${{ vars.OVH_VPS_SSH_IP}}
          SSH_PORT: ${{ vars.OVH_VPS_SSH_PORT}}
          SSH_USERNAME: ${{ vars.OVH_VPS_SSH_USERNAME}}
        run: |
          echo "Hello world"