name: Deploy Hugo Website
on: [ push ]
jobs:
#  Build:
#    runs-on: ubuntu-latest
#    container:
#      image: hugomods/hugo:0.125.2
#    steps:
#      - name: checkout repo
#        uses: actions/checkout@v4
#      - name: hugo build
#        run: |
#          cd /__w/Shitbeer/Shitbeer
#          hugo
#      - name: hugo build upload
#        uses: actions/upload-artifact@v4
#        with:
#          name: hugo-build
#          retention-days: 1
#          path: |
#            public
  Deploy:
    runs-on: ubuntu-latest
#    needs: Build
    steps:
#      - name: hugo build download
#        uses: actions/download-artifact@v4
#        with:
#          name: hugo-build
      - name: hugo deploy
        env:
          SSH_PRIVATE_KEY: ${{ secrets.OVH_VPS_SSH_PRIVATE_KEY }}
          SSH_IP: ${{ vars.OVH_VPS_SSH_IP }}
          SSH_PORT: ${{ vars.OVH_VPS_SSH_PORT }}
          SSH_USERNAME: ${{ vars.OVH_VPS_SSH_USERNAME }}
        run: |
          mkdir ~/.ssh && touch ~/.ssh/known_hosts
          ssh-keyscan -p "${SSH_PORT}" "${SSH_IP}" >> ~/.ssh/known_hosts
          echo "${SSH_PRIVATE_KEY}" > id_rsa && chmod 400 id_rsa
          rsync -avz --delete -e "ssh -p ${SSH_PORT} -i ./id_rsa" public/ ${SSH_USERNAME}@${SSH_IP}:~/public/