name: Deploy Hugo Website
on: [push]
jobs:
  Deploy-Hugo-Website:
    runs-on: ubuntu-latest
    container:
      image: hugomods/hugo:0.125.2
    steps:
      - env:
          SSH_PRIVATE_KEY: ${{ secrets.OVH_VPS_SSH_PRIVATE_KEY}}
          SSH_IP: ${{ vars.OVH_VPS_SSH_IP}}
          SSH_PORT: ${{ vars.OVH_VPS_SSH_PORT}}
          SSH_USERNAME: ${{ vars.OVH_VPS_SSH_USERNAME}}
        run: |
          ssh-add - <<< "${SSH_PRIVATE_KEY}"          
          hugo && rsync -avz --delete -e "ssh -p ${SSH_PORT}" public/ ${SSH_USERNAME}@${SSH_IP}:~/www/