name: Deploy Hugo Website
on: [push]
jobs:
  Deploy-Hugo-Website:
    runs-on: ubuntu-latest
    steps:
      - with:
          SSH_PRIVATE_KEY: ${{ secrets.OVH_VPS_SSH_PRIVATE_KEY}}
        run: |
          echo "Hello world"