name: Deploy Hugo Website
on: [push]
jobs:
  Deploy-Hugo-Website:
    runs-on: ubuntu-latest
    steps:
      - env:
          SSH_PRIVATE_KEY: ${{ secrets.OVH_VPS_SSH_PRIVATE_KEY}}
          OVH_VPS_SSH_IP: ${{ vars.OVH_VPS_SSH_IP}}
          OVH_VPS_SSH_PORT: ${{ vars.OVH_VPS_SSH_PORT}}
        run: |
          echo $OVH_VPS_SSH_IP
          echo $OVH_VPS_SSH_PORT